spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.107:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 192.168.0.110
    port: 5672
    username: guest
    password: guest 
  redis:
    host: 192.168.0.110
    port: 6379  
server:
  port: 8082      
env:
  devoooooo68kkkkkk
